disabled_rules:
    - conditional_returns_on_newline
    - redundant_string_enum_value
    - pattern_matching_keywords
    - trailing_closure
    - multiple_closures_with_trailing_closure
    - closure_end_indentation
    - notification_center_detachment
    - trailing_whitespace
    
opt_in_rules:
    - attributes
    - closure_end_indentation
    - closure_spacing
    - conditional_returns_on_newline
    - empty_count
    - explicit_init
    - fatal_error_message
    - force_unwrapping
    - multiline_parameters
    - operator_usage_whitespace
    - overridden_super_call
    - pattern_matching_keywords
    - private_outlet
    - prohibited_super_call
    - redundant_nil_coalescing
    - single_test_class
    - sorted_imports
    - switch_case_on_newline
    - trailing_closure
    - unneeded_parentheses_in_closure_argument

type_name:
    validates_start_with_lowercase: false
    min_length: 4
    max_length:
        warning: 60
        error: 80
    
line_length:
  warning: 170
  error: 200
  ignores_function_declarations: true
  ignores_urls: true
      
function_body_length:
  warning: 100
  error: 160
     
force_cast:
  severity: error

force_try:
  severity: error
  
force_unwrapping:
  severity: error
     
excluded:
    - Carthage
    - Pods
    - Facebook-iOS/BundleFiles
    - Facebook-iOS/Resources/Localization
    - vendor
    - Facebook-iOSUITests/Utilities/SnapshotHelper.swift
    - Facebook-iOS/*/AppDelegate.swift
    - Facebook-iOS/*/SceneDelegate.swift
    
identifier_name:
    excluded:
    - id
    - to
    - in
    - at
    - of
    - up
    
cyclomatic_complexity:
  ignores_case_statements: true
